name: dbus_wifi
description: |
  A simple library to connect to Wi-Fi networks using D-Bus on Linux.
  This library is intended for use with the dbus package in Dart and Flutter.
version: 0.0.6
repository: https://github.com/akshaybabloo/dbus_wifi

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  linux:

dependencies:
  dbus: ^0.7.11
  dart_console: ^4.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2

executables:
  dbus-wifi: dbus_wifi
